version: '3.8'

services:
  maria:
    image: docker.io/bitnami/mariadb:10.6
    container_name: mariadb
    ports:
      - "3307:3306"
    volumes:
      - ~/docker/mariadb/etc/mysql/conf.d:/etc/mysql/conf.d:ro
      - ~/docker/mariadb/var/lib/mysql:/var/lib/mysql
      - ~/docker/mariadb/var/log/maria:/var/log/maria
    environment:
      - TZ="Asia/Seoul"
      - ALLOW_EMPTY_PASSWORD=no
      - MARIADB_ROOT_PASSWORD=qwe1212!Q
      - MARIADB_DATABASE=freelancer_local
      - MARIADB_USER=freelancer_local
      - MARIADB_PASSWORD=freelancer_local
    restart: always

  redis:
    image: redis:latest
    networks:
      - freelancer_network
    ports:
      - "6379:6379"

volumes:
  mariadb_data:

networks:
  freelancer_network:
    driver: bridge
